name: CI

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: javanile/make-action@main
      - uses: stefanzweifel/git-auto-commit-action@v4
